version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment: 
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/postgres?schema=public
      - PORT=5000
      - DEBUG=route:*,server,db
  db:
    image: "postgres:latest"
    environment: 
      - POSTGRES_PASSWORD=mysecretpassword

  frontend:
    build:
      context: ./../projektname-frontend
      dockerfile: ./../projektname-frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:8080"
